BioDataWeb/Models/Credentials.cs
using System.ComponentModel.DataAnnotations;

namespace BioDataWeb.Models
{
    public class Credentials
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string FirstName { get; set; }
        
        [Required]
        public string LastName { get; set; }

        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only Numbers are allowed!")]
        [StringLength(11, ErrorMessage = "The Cell No. cannot exceed 11 digits!")]
        public string CellNo { get; set; }

        public DateTime DateTimeCreated {get; set; } = DateTime.Now;
    }
}

BioDataWeb/Models/ErrorViewModel.cs
namespace BioDataWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BioDataWeb/Controllers/BioDataController.cs
using BioDataWeb.Data;
using BioDataWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;

namespace BioDataWeb.Controllers
{
    public class BioDataController : Controller
    {
        private readonly ApplicationDbContext _db;

        public BioDataController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Credentials> UserInfo = _db.PersonalData;
            return View(UserInfo);
        }

        //Get
        public IActionResult CreateUser()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post
        public IActionResult CreateUser(Credentials obj)
        {
            if (obj.FirstName == obj.LastName && obj.LastName != null && obj.FirstName != null)
            {
                ModelState.AddModelError("CustomError", "First name and Last name can't be same!");
            }
            if (ModelState.IsValid)
            {
                _db.PersonalData.Add(obj);
                _db.SaveChanges();
                TempData["Success"] = "Category Created successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult EditUser(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var UserInfoFromDb = _db.PersonalData.Find(id);
            if(UserInfoFromDb == null)
            {
                return NotFound();
            }
            return View(UserInfoFromDb);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post
        public IActionResult EditUser(Credentials obj)
        {
            if (obj.FirstName == obj.LastName && obj.LastName != null && obj.FirstName != null)
            {
                ModelState.AddModelError("CustomError", "First name and Last name can't be same!");
            }
            if (ModelState.IsValid)
            {
                _db.PersonalData.Update(obj);
                _db.SaveChanges();
                TempData["Success"] = "Category Updated successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult RemoveUser(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var UserInfoFromDb = _db.PersonalData.Find(id);
            if (UserInfoFromDb == null)
            {
                return NotFound();
            }
            return View(UserInfoFromDb);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //Post
        public IActionResult RemoveUser(Credentials obj)
        {
            if (obj.FirstName == obj.LastName && obj.LastName != null && obj.FirstName != null)
            {
                ModelState.AddModelError("CustomError", "First name and Last name can't be same!");
            }
            if (ModelState.IsValid)
            {
                _db.PersonalData.Remove(obj);
                _db.SaveChanges();
                TempData["Success"] = "Category removed successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

BioDataWeb/Controllers/HomeController.cs
using BioDataWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BioDataWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BioDataWeb/Views/BioData/CreateUser.cshtml
@model Credentials

<form method="post">
    <div class="container p-3 mt-5" style="border-style:solid;">
        <div class="row mt-2 p-3 mb-3">
            <h3 class="form-label text-primary">Create User</h3>
        </div>
        <div asp-validation-summary="All" class="text-danger">

        </div>
        <div class="row mt-3 p-4">
            <label class="form-label text-primary" style="font-size:18px;">First Name</label>
            <input class="form-control" type="text" asp-for="FirstName" />
            <span class="text-danger" asp-validation-for="FirstName"></span>
        </div>
        <div class="row mt-2 p-4">
            <label class="form-label text-primary" style="font-size:18px;">Last Name</label>
            <input class="form-control" type="text" asp-for="LastName" />
            <span class="text-danger" asp-validation-for="LastName"></span>
        </div>
        <div class="row mt-2 p-4">
            <label class="form-label text-primary" style="font-size:18px;">Cell No.</label>
            <input class="form-control" type="text" asp-for="CellNo"/>
            <span class="text-danger" asp-validation-for="CellNo"></span>
        </div>
        <button class="btn btn-success ms-2" type="submit" style="width:100px;">Create</button>
        <a class="btn btn-secondary ms-2" style="width:100px;" asp-controller="BioData" asp-action="Index">Back</a>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BioDataWeb/Views/BioData/EditUser.cshtml
@model Credentials

<form method="post">
    <div class="container p-3 mt-5" style="border-style:solid;">
        <div class="row mt-2 p-3 mb-3">
            <h3 class="form-label text-primary">Edit User</h3>
        </div>
        <div asp-validation-summary="All" class="text-danger">
        </div>
        <div class="row mt-3 p-4">
            <label class="form-label text-primary" style="font-size:18px;">First Name</label>
            <input class="form-control" type="text" asp-for="FirstName" />
            <span class="text-danger" asp-validation-for="FirstName"></span>
        </div>
        <div class="row mt-2 p-4">
            <label class="form-label text-primary" style="font-size:18px;">Last Name</label>
            <input class="form-control" type="text" asp-for="LastName" />
            <span class="text-danger" asp-validation-for="LastName"></span>
        </div>
        <div class="row mt-2 p-4">
            <label class="form-label text-primary" style="font-size:18px;">Cell No.</label>
            <input class="form-control" type="text" asp-for="CellNo" />
            <span class="text-danger" asp-validation-for="CellNo"></span>
        </div>
        <button class="btn btn-success ms-2" type="submit" style="width:100px;">Update</button>
        <a class="btn btn-secondary ms-2" style="width:100px;" asp-controller="BioData" asp-action="Index">Back</a>
    </div>
</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BioDataWeb/Views/BioData/Index.cshtml
@model IEnumerable<Credentials>;
@{
    ViewData["Title"] = "Index";
}



<div class="container p-3">
    <div class="row mt-2">
        <div class="col-6 p-2">
            <h3>User List</h3>
        </div>
        <div class="col-6">
            <a class="btn btn-success float-end" style="width:180px;text-decoration:none; font-size:20px; text-align:center;" asp-controller="BioData" asp-action="CreateUser">
                <i class="bi bi-plus-circle me-2"></i>  Create User
             </a>
        </div>
    </div>
    <div class="row mt-4 p-3">
        <table class="table-bordered table-light" style="text-align:center;">
            <thead>
                <th style="width:30%;">First Name</th>
                <th style="width:30%;">Second Name</th>
                <th style="width:25%;"> Cell No.</th>
                <th style="width:15%;">Action</th>
            </thead>
            
            <tbody>
                    @foreach(var obj in Model)
                    {
                        <tr>
                            <td>
                              @obj.FirstName 
                            </td>
                            <td>
                               @obj.LastName
                            </td>
                            <td>
                               @obj.CellNo 
                            </td>
                            <td>
                            <a class="btn btn-info m-1 btn-outline-dark" asp-controller="BioData" asp-action="EditUser" asp-route-id="@obj.Id"><i class="bi bi-pencil-fill"></i></a>
                            <a class="btn btn-danger m-1 btn-outline-dark" asp-controller="BioData" asp-action="RemoveUser" asp-route-id="@obj.Id"><i class="bi bi-trash-fill"></i></a>
                            </td>
                        </tr>
                    }
              
            </tbody>

        </table>
    </div>

</div>

BioDataWeb/Views/BioData/RemoveUser.cshtml
@model Credentials

<form method="post">
    <div class="container p-3 mt-5" style="border-style:solid;">
        <div class="row mt-2 p-3 mb-3">
            <h3 class="form-label text-primary">Delete User</h3>
        </div>
        <div asp-validation-summary="All" class="text-danger">
        </div>
        <div class="row mt-3 p-4">
            <label class="form-label text-primary" style="font-size:18px;">First Name</label>
            <input class="form-control" type="text" asp-for="FirstName"  readonly/>
            <span class="text-danger" asp-validation-for="FirstName"></span>
        </div>
        <div class="row mt-2 p-4">
            <label class="form-label text-primary" style="font-size:18px;">Last Name</label>
            <input class="form-control" type="text" asp-for="LastName" readonly/>
            <span class="text-danger" asp-validation-for="LastName"></span>
        </div>
        <div class="row mt-2 p-4">
            <label class="form-label text-primary" style="font-size:18px;">Cell No.</label>
            <input class="form-control" type="text" asp-for="CellNo" readonly/>
            <span class="text-danger" asp-validation-for="CellNo"></span>
        </div>
        <button class="btn btn-success ms-2" type="submit" style="width:100px;">Delete</button>
        <a class="btn btn-secondary ms-2" style="width:100px;" asp-controller="BioData" asp-action="Index">Back</a>
    </div>
</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BioDataWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BioDataWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BioDataWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/SuperHero.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BioDataWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BioData" asp-action="Index">User ID</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted mt-auto">
        <div class="container">
            &copy; 2022 - BioDataWeb 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BioDataWeb/Views/Shared/_Notifications.cshtml
    
    @if(TempData["Success"] !=null)
    {
        <script src="~/lib/jquery/dist/jquery.min.js"> </script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
      
        <script type="text/javascript">
            toastr.success('@TempData["Success"]');
        </script>
    }